name: Validate 'setup-xcode'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  xcode-versions:
    name: xcode versions
    runs-on: macos-latest
    strategy:
      matrix:
        xcode-version: ['11.7', latest, latest-stable]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: ./
      with:
        xcode-version: ${{ matrix.xcode-version }}
